### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Waynerbee** [ElasticBottle/Badminton_Avalability_checker#9]
DevTools listening on ws://127.0.0.1:50773/devtools/browser/68bf2a13-2677-48aa-894d-a912877e13cb
Traceback (most recent call last):
  File "C:\Users\wayne\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\wayne\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\wayne\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Waynerbee** [comment]
Sorry, I realised it was because my Python was outdated, I just had to delete the old python 2.7 version, and reinstall the newer 3.6.7 version.

**Comment by ElasticBottle** [comment]
Hey Wayne, thanks for opening the issue!

Let me know if you're still running into the issue, 

I run Linux now so it's hard for me to reproduce. Might try it if time permits sometime over the weekend or two.

**Comment by Waynerbee** [comment]
Yes, I tried rerunning and updating my python too, but still facing this same issue.

**Comment by Waynerbee** [comment]
Seems like I got a new error now... 

 pip install pandas
 
 
Collecting pandas
  Using cached pandas-1.5.2.tar.gz (5.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.        
  │ exit code: 1
  ╰─> [243 lines of output]

**Comment by ElasticBottle** [comment]
lmk if you ever fix this! Happy to review any PR
